### ISSUE TITLE
Multiple instances in production

### ISSUE THREAD

**Issue by mmallejac** [timlegge/docker-foswiki#15]
Hello Tim,

First I wish you a very hapy new year 2020 !

I've improved my knowledge about docker and docker-compose. Especially about [Traefik](https://docs.traefik.io/) : this tool is one of the most used proxy application used in combination with containers, Docker but also Kubernetes, Rancher and so on. It is super nice, for instance it can handle the HTTPS certificate handling for you.

I have to run multiple Foswiki instances and having Traefik in the equation adds some constrains, especially on the Docker networks : all services proxied by Traefik _have to run on the same network_.

The diagram on the top of [this page](https://hollo.me/devops/routing-to-multiple-docker-compose-development-setups-with-traefik.html) illustrates this very well : the blue network that links both Nginx to Traefik is the common network, but inside each service another network is defined, so that only the strictly necessary traffic goes on the common network.

So with this in mind, I think we could improve the Foswiki service architecture a little bit. The main change would be to exclude Nginx from the Dockerfile and include it as a standalone image, as Solr is already.

Would you agree that we move into this direction ?

Cheers,
Michel

**Comment by timlegge** [comment]
Happy New Year to you as well.

I have no issue with looking at that.  With what I recently learned with
docker compose myself its probably the right move.

**Comment by MichaelDaum** [comment]
Does that mean nginx won't be able to serve static foswiki files anymore?

**Comment by mmallejac** [comment]
Hello Michael,

Nginx is fine :-)

We're talking here about the Docker architecture for the Foswiki service.
So far we have a Dockerfile (a container) that includes Foswiki and Ngnix
and a docker-compose.yml file that adds Solr to it. The Nginx should be
moved out of the Dockerfile to the docker-compose.yml file, the result will
be a docker-compose'd Foswiki service made of 3 containers : Nginx,
Foswiki, and Solr.

That will allow a better isolated Foswiki service (internal and external
networks, only Nginx exposed to the external one) and a better scalability
(run multiple instances of the Foswiki service on the same server).

Le mer. 8 janv. 2020 à 08:23, Michael Daum <notifications@github.com> a
écrit :

**Comment by MichaelDaum** [comment]
I see now. My docker knowledge is very very limitted. So I wonder wether nginx would be able to access css, js and thumbnail images directly while running on a different container than foswiki itself. 

Btw for running multiple foswiki instances in a very resource friendly way have a look at https://foswiki.org/Extensions/VirtualHostingContrib. This is a solution based on named virtual hosts served by the same server.

**Comment by mmallejac** [comment]
Yes, that will be fine, this looks like the standard way to do it.
I didn't know about VirtualHostingContrib ! I'll look at it

BTW, many thanks for all you do for Foswiki :-)
An off-topic question : is there a way to prevent the browser to close
while a topic is being edited ? Some web sites do this and ask confirmation
before closing, very handy.

Le mer. 8 janv. 2020 à 09:31, Michael Daum <notifications@github.com> a
écrit :

**Comment by MichaelDaum** [comment]
Yes, that will be in place for the new NatEditPlugin I am working on. And this not only for the TinyMCE backend.

**Comment by mmallejac** [comment]
Great ! can't wait for it :-)

Le mer. 8 janv. 2020 à 11:44, Michael Daum <notifications@github.com> a
écrit :

**Comment by mmallejac** [comment]
Hello Tim,

Hope you're doing good.

I am about to submit you a PR that will allow to have multiple instances running on the same server.

Here I face 2 choices : 
- a fully-working solution, ready for Traefik, the most widely-used proxy for containers 
- a half-way one, so that the docker-compose remains free of Traefik configs, but which leaves the overall config more complex an requires more explanations.

The first has my preference : it simplify things quite a lot. If someone wants to run multiple instances but not using Traefik, it won't hurt since the extra lines for Traefik will not harm (a few "labels" lines).

Also if running only one instance, no worries as well.

Let me know if you're ok with that !
Thanks in advance,
Michel

**Comment by timlegge** [comment]
send the first and I can take a look

**Comment by mmallejac** [comment]
Done !

Le mer. 4 mars 2020 à 18:09, Timothy Legge <notifications@github.com> a
écrit :
