### ISSUE TITLE
"Cannot load package 'Email::MIME::Header::AddressList'" in email.

### ISSUE THREAD

**Issue by rec** [timlegge/docker-foswiki#16]
This is clearly well-known to you - see https://foswiki.org/Support/Question1997

Did you ever get past this?

Thanks for your useful package!

**Comment by timlegge** [comment]
I have never gotten back to it.  I will try to take a look though.  If you
find anything a PR would be appreciated.

**Comment by MichaelDaum** [comment]
This is part of Email::MIME, a core dependency. See https://github.com/foswiki/distro/blob/master/core/lib/Foswiki/Contrib/core/DEPENDENCIES#L21

**Comment by rec** [comment]
So it should just work. And we checked on the server that that package is installed.

A clue I am not capable of following:

It claims to be missing `Email/Address/XS.pm`

    Can't locate Email/Address/XS.pm in @INC
    (you may need to install the Email::Address::XS module)
    (@INC contains: /var/www/foswiki/lib . /usr/local/lib/perl5/site_perl
    /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl
    /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl
    /var/www/foswiki/lib/CPAN/lib)
    at /usr/share/perl5/vendor_perl/Email/MIME/Header/AddressList.pm line 9.

But here's the location, we think:

    total 120K   
    drwxr-xr-x    5 root     root        4.0K Nov 30 02:11 .
    drwxr-xr-x    1 root     root        4.0K Nov 30 14:44 ..
    -r--r--r--    1 root     root       25.6K Dec 31  2018 Address.pm
    drwxr-xr-x    2 root     root        4.0K Nov 30 02:11 Date
    drwxr-xr-x    3 root     root        4.0K Nov 30 02:11 MIME
    -r--r--r--    1 root     root       46.4K Aug 31  2017 MIME.pm
    -r--r--r--    1 root     root        5.4K Aug 10  2015 MessageID.pm
    drwxr-xr-x    2 root     root        4.0K Nov 30 02:11 Simple
    -r--r--r--    1 root     root       15.8K Jun  6  2018 Simple.pm
    bash-5.0# pwd
    /usr/share/perl5/vendor_perl/Email

So `Address.pm` exists, but the directory `Address/` doesn't.

**Comment by timlegge** [comment]
Thanks

That helps.  I will need to roll the alpine package but I may be able to
send you an alpine package to try in the next day or so.

Tim

**Comment by timlegge** [comment]
I have a package created.  You will need to unzip it and get it into your container

apk add perl-email-address-xs-1.04-r0.apk

I have not tested and I will try it later today and if it works roll a new version of the container.

[perl-email-address-xs-1.04-r0.apk.zip](https://github.com/timlegge/docker-foswiki/files/4225727/perl-email-address-xs-1.04-r0.apk.zip)

**Comment by timlegge** [comment]
I have a package created.  You will need to unzip it and get it into your container

apk add perl-email-address-xs-1.04-r0.apk

I have not tested and I will try it later today and if it works roll a new version of the container.

[perl-email-address-xs-1.04-r0.apk.zip](https://github.com/timlegge/docker-foswiki/files/4225727/perl-email-address-xs-1.04-r0.apk.zip)

**Comment by rec** [comment]
I might not be able to fully try it out, unfortunately - we're probably going for Bookstack as we have to get this done and I have a working installation of that ready too.

So I can't actually deploy onto a server that can emit email, so there will be no way to test it.  :-/

**Comment by rec** [comment]
Ah, your other message didn't pop up before this one!

Ach, juggling too many things.  I'll see if I can give it a try on the other server...

**Comment by timlegge** [comment]
Fixed in version v1.10 (v1.0.10)

docker pull timlegge/docker-foswiki:v1.10

I have included a local copy of the perl-email-address-xs package for Alpine untill I am able to get tit accepted by the Alpine team

**Comment by timlegge** [comment]
BTW: I tested with and without this package installed against a google mail server using a username and password to login to the gmail smtp server using port 587 and StartTLS and it worked fine with the package and not at all (no error) without the package/module

**Comment by rec** [comment]
Brilliant!

So what was the issue?  It certainly baffled me.

**Comment by timlegge** [comment]
the perl module you mentioned was missing

**Comment by timlegge** [comment]
let me know if that solves your issue

**Comment by rec** [comment]
Interesting!  We did try to install it within the container, but clearly you got further.

Hopefully I will get to try it soon - otherwise, later.

**Comment by timlegge** [comment]
I did too but this version is the first time I have gotten email to work at
all.  let me know if it works for you when you try it

**Comment by timlegge** [comment]
I see why it fails in the container by installing the apk file that I gave you.  It looks like the version of perl incremented in alpine edge so building on that version would not work for the last container version.  You can see that by:

perl -e "use Email::Address::XS"

**Comment by timlegge** [comment]
Fixed Version 1.10 and 1.11
