### ISSUE TITLE
Request:  Open ID Connect Authentication with OpenIDLoginContrib 

### ISSUE THREAD

**Issue by modem7** [timlegge/docker-foswiki#17]
To be more secure, the ability to setup 2fa would be greatly appreciated. 

Unfortunately it requires the following dependencies: 

MIME::Base64 |   | Required
LWP::UserAgent | >=6.15 | Required for OAuth 2 Server Flow
Crypt::JWT | >=0.010 | Required for JWT signature verification
Crypt::Random |   | Required for cryptographically secure nonces
JSON |   | Required

See: https://foswiki.org/Extensions/OpenIDLoginContrib

Would it be possible to add these dependencies to the image at all? I understand you had to do some work with Alpine, unsure if this would be required. 

Thanks!

**Comment by timlegge** [comment]
Should be easy.   let me take a look

**Comment by timlegge** [comment]
>
> MIME::Base64 |   | Required
>
Included already

> LWP::UserAgent | >=6.15 | Required for OAuth 2 Server Flow
>
Included already

> Crypt::JWT | >=0.010 | Required for JWT signature verification
>
Crypt::Random |   | Required for cryptographically secure nonces
>
Will need to package these two for Alpine and get them accepted.  Should
just take a day or two.


> JSON |   | Required
>
Included already

By the way I use SamlLoginContrib if that is useful to you.  The 2F
authentication takes place during the authentication with Microsoft Azure
(or Google, or other Identity Provider) and when its done there you are
automatically authenticated on Foswiki.

Tim

**Comment by modem7** [comment]
Oh awesome! I wasn't aware samllogincontrib did that!

I'll definitely investigate that as well!

Thank you for looking into this as well!

**Comment by timlegge** [comment]
As the 2FA is done at the Identity provider SamlLoginContrib doesn't
do much with it.  It merely trusts that the Identity Provider has
properly authenticated you.  If your rules at the Identity provider
says to do 2FA you are not authenticated until that happens.

Tim

**Comment by timlegge** [comment]
Alpine packages have been submitted and just waiting to be merged.  I will
roll a release after that

**Comment by timlegge** [comment]
version 1.12 released

timlegge/docker-doswiki:v1.12

**Comment by modem7** [comment]
Thank you! Will give it a whirl now!
