### ISSUE TITLE
Can't find mentioned .env-file

### ISSUE THREAD

**Issue by araschke** [timlegge/docker-foswiki#21]
Hello Timothey,

thanks for your valuable work! 

In your README you mention a .env-file that should be copied and modified. Unfortunately, I can't find this file anywhere. Could you provide that file please? 

Regards,
   Alexander

**Comment by timlegge** [comment]
@mmallejac did we forget to detail what this .env was?

I can look later today if you are not available

**Comment by mmallejac** [comment]
Yes Alexander, you're totally right.
There is still a little gap between my production setup and the repo.

Let me fix that.

**Comment by mmallejac** [comment]
Latest commit should do the job : let us know !

**Comment by araschke** [comment]
Yes, fine thanks!
