### ISSUE TITLE
when checking the setup of solr, an error occurs

### ISSUE THREAD

**Issue by dignin** [timlegge/docker-foswiki#22]
Connect to foswiki container
Test the indexing
cd /var/www/foswiki/tools
./solrindex Topic=WebHome
It should show you the files being indexed

resuls in 

/var/www/foswiki/tools # ./solrindex Topic=WebHome
ERROR: Could not parse JSON response: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "Can't connect to sol...") at /var/www/foswiki/lib/WebService/Solr/Response.pm line 40.
 Can't connect to solr:8983 (Name does not resolve)

**Comment by timlegge** [comment]
The documentation needs a update and I need to sync with dockerhub

Need instruction for a fresh start user with no github check out @mmallejac

**Comment by mmallejac** [comment]
Hello Shawn,

Thanks for reporting this.
Quite busy this week, sorry about this delay.
I've just modified the `.env` file that wasn't correct.
Still the error is present. I'll go deeper into this later in the week-end.

**Comment by timlegge** [comment]
I think this one may have been related to the solr container actually having a different hostname with the works Shawn has been doing in PR #23
