### ISSUE TITLE
Pre-login the help pages and System web redirect loop

### ISSUE THREAD

**Issue by timlegge** [timlegge/docker-foswiki#26]
Prior to login clicking on the System Web or the Help Menu items results in a redirect loop:

http://docker-foswiki.local:8765/bin/oops/System/AdminDocumentationCategory?template=oopsredirectdenied;def=redirect_denied;param1=http://docker-foswiki.local:8765/Main/WebHome;param2=http://localhost

**Comment by MichaelDaum** [comment]
Is this happening as a WikiGuest or anytime, even when authenticated? If not authenticated yet, AutoRedirectPlugin might kick in trying to obfuscate any access to the System web. The next thing to look for why this redirect fails is DefaultUrlHost not being set correctly, or adding additional urls to PermittedRedirectHostUrls.

**Comment by timlegge** [comment]
Just as wikiguest.  as authenticated it works fine for me.   likely the URL
thanks
