### ISSUE TITLE
why not enable xsendfile in nginx as it is bundled anyway?

### ISSUE THREAD

**Issue by MichaelDaum** [timlegge/docker-foswiki#27]
https://github.com/timlegge/docker-foswiki/blob/460b40d4ecd53226ade695f1d2e1b57e9b408383/https/nginx.default.conf#L61

viewfile based protection is really bad infact.

**Comment by timlegge** [comment]
So it is.  will do.  It was a large pain to get it working as the nginx named locations did not work for some reason.  Did not notice that xsendfile was installed. 

can you take a look at #26 as I could not sort that last night.

**Comment by timlegge** [comment]
Hi @MichaelDaum 

Is this correct?  Nginx seems to choke on the         {XSendFileContrib}{Header} = 'X-Accel-Redirect';

Tim
```
    location /pub {                                                       
        {XSendFileContrib}{Header} = 'X-Accel-Redirect';                  
        {XSendFileContrib}{Location} = '/files';                          
        rewrite ^/pub/(.*)$ /bin/xsendfile/$1;                            
    } 
```

**Comment by MichaelDaum** [comment]
The {XsendFileContrib} settings go into LocalSite.cfg.

**Comment by timlegge** [comment]
Wondered about that.  Only other thing I could think was the nginx was
supposed to save some sort of variable.  Makes sense now.

**Comment by timlegge** [comment]
Fixed in master
