### ISSUE TITLE
tag v1.13 v1.14 points to master that is breaked (xsendfile don't work, cause it needs perl mmagic)

### ISSUE THREAD

**Issue by rogeriomachado666** [timlegge/docker-foswiki#28]
tag v1.13 v1.14 points to master that is breaked (xsendfile don't work, cause it needs perl mmagic). Image v1.13,v1.14 on docker hub don't work 
tag 1.13 is ok

**Comment by timlegge** [comment]
Thanks for the update.  I realized I screwed up the tagging.  I will try to
fix it tonight.  I will also fix the perl magic issue.

Tim
