### ISSUE TITLE
WebChanges don't work as expected

### ISSUE THREAD

**Issue by rogeriomachado666** [timlegge/docker-foswiki#29]
WebChanges don't work as expected. Sometimes freezes the browser
commit 83021e5bde678b8d22e6e8cff47fd3819d684e6c

**Comment by timlegge** [comment]
Do you have more details on what exactly is not working?  Last time I
looked it appeared to be working.

**Comment by timlegge** [comment]
So, the story is likely:

Follow the instructions at:
https://foswiki.org/Extensions/SolrPlugin#Using_Solr_for_WebSearch_44_WebChanges_and_Main.WikiUsers

```
$Foswiki::cfg{Plugins}{AutoTemplatePlugin}{ViewTemplateRules} = {
...
  'WebChanges' => 'WebChangesView',
  'SiteChanges' => 'SiteChangesView',
  'WebSearch' => 'SolrSearchView',
  'WikiUsers' => 'SolrWikiUsersView',
...
};
```
Then in SolrPlugin enable:

{SolrPlugin}{EnableOnSaveUpdates}:
{SolrPlugin}{EnableOnUploadUpdates}:

If you have much content you will likely also need to go into the docker container and run a full index:
https://foswiki.org/Extensions/SolrPlugin#Setting_up_an_indexing_strategy
Full indexing
./solrindex mode=full optimize=on

**Comment by timlegge** [comment]
This is likely a documentation issue if you can confirm that that works as expeted.

Tim

**Comment by MichaelDaum** [comment]
Better don't activate {SolrPlugin}{EnableOnSaveUpdates}: {SolrPlugin}{EnableOnUploadUpdates}. This will severely impact interactive performance. Instead activate iwatch to perform realtime indexing offline. See https://foswiki.org/Extensions/SolrPlugin#Realtime_indexing

**Comment by timlegge** [comment]
Ivenever noticed any issues in my installation but I will take a look at
enabling iwatch

**Comment by timlegge** [comment]
Just waiting for iwatch to roll into the alpine repo.  https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/8120   I should be able to sort it out and document anything required after that.
