### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by gurpal2000** [timlegge/docker-foswiki#30]
Hi in your dockerfile you have "DefaultUrlHost" set twice.
thx

**Comment by mmallejac** [comment]
Hello !

Many thanks, I'll take care of that.

**Comment by mmallejac** [comment]
Hi Tim,

I have not done much for a while here.
Would you like me to review the readme.md ? Maybe a little something should be mentioned about the CAPROVER thing.

**Comment by timlegge** [comment]
Please go ahead :-)

**Comment by mmallejac** [comment]
Fixed with [75a8e4f](https://github.com/timlegge/docker-foswiki/commit/75a8e4f63c8a2a30b6bc1bf0d2cb0555e98fcff3)
