### ISSUE TITLE
Problem with ImagePlugin build fails due to dependency

### ISSUE THREAD

**Issue by zarafc** [timlegge/docker-foswiki#34]
Hello

Thanks Tim for this contribution

I have been using this distrubition for a while without issue but  coming back to it in Septemeber I have problems with the Dockerfile unless I comment out the ImagePlugin installation

tools/extension_installer ImagePlugin -r -enable install

The installer cannot find the Image::Magick dependency.

I think it is a problem with teh Plugin itself rather than your code but I thought it is worth pointing out to you anyway

Regards

**Comment by timlegge** [comment]
Did you try the actual Docker image sits available on Docker hub

I have some issues sometimes because alpine edge is a moving target.  I can
take a look tonight.

Tim

**Comment by timlegge** [comment]
I believe the issue is https://gitlab.alpinelinux.org/alpine/aports/-/issues/11977 Alpine Edge has upgraded to perl 5.32 and perlmagick needs to be rebuilt.  I am working with the alpine guys to resolve

**Comment by timlegge** [comment]
@zarafc Alpine has fixed the issue and you should be fine.  Note, alpine edge now used perl 5.32 so you will need to test

**Comment by zarafc** [comment]
Thanks for the reply. 

I just tried (Oct-1 ) but unfortunately _tools/extension_installer ImagePlugin -r -enable install_ still does not find Image::Magick and so the ImagePlugin does not get installed.

**Comment by timlegge** [comment]
Is there a particular reason you are installing from the Docker file?

You can use:  I will try it again - sometimes there are build issues
because of an issue at foswiki.org.

Also, try --no-cache in your docker build command

docker run -idt -p 80:80 timlegge/docker-foswiki

**Comment by zarafc** [comment]
First I tried it from the Dockerfile , as you have it. The build runs but skips the ImagePlugin because of the missing module.
Then I also tried to install the plugin then from the CLI with the extension_installer. In both case the Image::Magick module is not found. Same if I use the configure interface. 
If the ImagePlugin is enabled then foswiki breaks returning a 502 error on the browser

docker run -idt -p 80:80 timlegge/docker-foswiki works but not a new build

**Comment by timlegge** [comment]
I see the perl-imagemagick-perlmagick package installing

The warning:

WARNING: > CPAN dependencies were detected, but will not be automatically
installed by the Web installer.  The following dependencies should be
manually resolved as required.

* Image::Magick

> The following configuration changes are needed to enable plugins.
These will be automatically applied when the configuration is saved.

Just means it did not install automatically:

perl -e 'use Image::Magick'

does not provide an error for me.

Tim

**Comment by zarafc** [comment]
Thanks for the reply
The architecture is x86_64 Linux

docker run -idt -p 80:80 timlegge/docker-foswiki works is fine and ImagePlugin is enabled and works 

However, I am using your Dockerfile but with some changes to adapt to our environment (non-root and extra features). So I have to build the image locally.

By chance have you rebuild your image since the upgrade to 5.32 ?

**Comment by timlegge** [comment]
Yes, the latest includes 5.32.  Send a MR and I can likely add your
customizations to the build.

**Comment by zarafc** [comment]
Yes I See
perl -e 'use Image::Magick'
does not give an error for me either now.

I got some good results though now
In configure the ImagePlugin was not enabled because the InagePluginModule was not set. 
So I pressed Reset an then re-enabled ImagePlugin.

Im not sure why ImagePlugin was not enabled from the start. I need to check further on my side

**Comment by zarafc** [comment]
All works well now. I probably had a browser cache to  clear.
Sorry for the delay with the reply and thanks again for your help

**Comment by timlegge** [comment]
No problem I think it was related to Alpine Linux package that needed to be rebuilt for the correct version of Perl
