### ISSUE TITLE
Lost login session. Required to login again.

### ISSUE THREAD

**Issue by zarafc** [timlegge/docker-foswiki#36]
Hi

I am experiencing some problems with the logon session. After logon I browse and edit as an authenticated user and after a while I am prompted to login again. I have tried this with both the OpenID LoginManager and also the default one and I get the same result.

Here I  authenticate as the site admin

$Foswiki::cfg{LoginManager} = 'Foswiki::LoginManager::TemplateLogin';
$Foswiki::cfg{Trace}{LoginManager} = 1;
$Foswiki::cfg{UserMappingManager} = 'Foswiki::Users::TopicUserMapping';

I get the following in the foswiki-error.log 
In the first case it finds my session and I continue as 'admin'

_SESSION ?(c):  ... Found session id 41b2e290d9efa1d371441e435682084f;
SESSION ?(c): _loadCreateCGISession called ...
SESSION 41b2e290d9efa1d371441e4356" while reading ..........
2020/10/24 07:37:09 [error] 40#40: *26 FastCGI sent in stderr: "82084f(c): AUTHUSER from session is admin
SESSION 41b2e290d9efa1d371441e435682084f(c): userLoggedIn called with admin - undef_

In the 2nd case it finds my session but then something changes and I become 'guest'. I am then asked to login again

_SESSION ?(c):  ... Found session id 41b2e290d9efa1d371441e435682084f;
SESSION ?(c): _loadCreateCGISession called ...
SESSION 554776ed2b1111da42708fe07a" while reading .....
2020/10/24 07:37:16 [error] 38#38: *53 FastCGI sent in stderr: "9758b5(c): No session, checking URI Params for a user
SESSION 554776ed2b1111da42708fe07a9758b5(c): Falling back to DEFAULT USER: guest
SESSION 554776ed2b1111da42708fe07a9758b5(c): userLoggedIn called with guest - undef_

Has anyone experience the same thing? 
Any ideas what could be going on

Thanks for your feedback

**Comment by timlegge** [comment]
My Foswiki installation using Docker works fine but does log me out after a while.  I have not looked at the logs to see what the messages look like but I may be able to today.  

Which auth type arer you using? Ldap, Local, SAML, etc.

@MichaelDaum might have some ideas.

Tim

**Comment by zarafc** [comment]
Thanks for the reply

First I tried with the OpenID login configured and noticed this behavior. But I get the same result even logged in as  the AdminUserLogin (admin)
Then I re-installed and set for just the local authentication. There are no users registered only the AdminUserLogin (admin) and I get the same logged in as admin.

**Comment by timlegge** [comment]
How long does it take before the session signs you out of the system?

**Comment by zarafc** [comment]
It is random, 
For the time I would say always less that 5 minutes
For page changes,sometimes after just 5-6 topic views or edits and other times after 20-30.  
For the browser, the logout occurs earlier on the Chrome browser but the logout also happens on Firefox.

I am generally clicking away randomly on pages in Main and System webs and creating topics in the Sandbox. I dont identify any particular topic or transaction that triggers this

**Comment by timlegge** [comment]
I just checked my prod instance and I dont see that or any errors like that.  I will spin up a fresh docker container here

**Comment by mmallejac** [comment]
Hello Tim,

Maybe that could be a good oportunity to include the latest modules
upgraded by Michael ?

I do not see these issues on my running instances.

Michel

Le lun. 26 oct. 2020 à 14:19, Timothy Legge <notifications@github.com> a
écrit :

**Comment by timlegge** [comment]
I just pushed timlegge/docker-foswiki:latest

I have been testing it for a bit but I caanot find any issues related to the session.  Seems to work fine when logged in with admin.

@mmallejac timlegge/docker-foswiki:latest should have the latest version of the plugins if you want to give it a spin.  Remember that if you want them in an existing volume you need to update via configure or do a migration

Tim

**Comment by zarafc** [comment]
I think I have found out what was happening on my side.
The setting _$Foswiki::cfg{Sessions}{UseIPMatching}_ is enabled by default (as written in the doc). 

Looking through the event.log I saw that the IP number was changing at the time when the session was lost.
By disabling this I have not seen a lost session yet.

**Comment by timlegge** [comment]
I've never run into that issue.  Since you're good now I will close the
issue
