### ISSUE TITLE
Problems installing DB_File

### ISSUE THREAD

**Issue by zarafc** [timlegge/docker-foswiki#39]
Hi
The Dockerfile contains the following to install DB_FILE. 
```
   rm -fr /var/cache/apk/APKINDEX.* && \
    perl -MCPAN -e 'install DB_File' && \
    perl -MCPAN -e "CPAN::Shell->notest('install', 'DB_File::Lock')" && \

```
I now get an error during the build

> /usr/bin/perl Makefile.PL -- OK
> Running make for P/PM/PMQS/DB_File-1.855.tar.gz
> make: /bin/sh: Operation not permitted
> make: *** [Makefile:418: blib/lib/.exists] Error 127
>   PMQS/DB_File-1.855.tar.gz
>   /usr/bin/make -- NOT OK

It worked fine for me in early January
What could be wrong here?
Thanks for your feedback

**Comment by timlegge** [comment]
Hi

This is due to a change in Alpine Linux docker that is not compatible with
your host.

https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements

Tim

**Comment by zarafc** [comment]
Hi 
Thanks for the reply.
Im running this on Openshift 3 with  non-root access.

What are my options?

**Comment by timlegge** [comment]
Upgrade :-)  Other options: change the version from alpine-edge to alpine v 3.12

I am not sure whether a version built on a newer host will work on an
older host.

Best bet is probably 3.12 but it might mean more changes to build some
perl modules from cpan (like is being done with DB_File.

Tim

**Comment by timlegge** [comment]
I pushed some changes to make 3.12 the base Alpine version that might fix the issue you are seeing

**Comment by zarafc** [comment]
Thanks, that great. I will check it out

**Comment by zarafc** [comment]
It is ok now. Thanks for your help
