### ISSUE TITLE
Issues when accessing via upstream proxy with additional path

### ISSUE THREAD

**Issue by smuskiew** [timlegge/docker-foswiki#41]
I've got docker-foswiki running well with the "stock" docker compose configuration, but am having a few issues when I try to put another (nginx) proxy in front of it and access foswiki thru that.  (It's possible some of this _could_ be in the foswiki app itself but figured I would try here since I am running via docker-foswiki 🙂 )

If I use an nginx proxy config with a separate virtual host name and no additional path info (for example "wiki.example.com" proxying to "http://my-docker-foswiki-host.example.cpm:8765" then it seems to "mostly" work, I have seen a couple random issues with some pages that seem to display a "dialog" type overlay (like "New" and "copy") sometimes not working but I'm thinking those may be browser-specific problems and/or issues with my internal HTTPS cert as I just tried again with a clean firefox install and they worked flawlessly.

The main issue I'm running into is if I attempt place an additional path in my upstream proxy (for example "home.example.com/wiki" proxying to "http://my-docker-foswiki-host.example.cpm:8765") then it seems like foswiki is rendering all the links without the "/wiki" component in the path so then none of the CSS/script URLs load and all the page content links that display are wrong (they all use "home.example.com/<WebName>/<page>").

I'm fairly certain I have my foswiki config/security settings correct, I definitely have all the possible URL variations set in `PermittedRedirectHostUrls`.  I'm also not certain if I'm missing something from my upstream proxy config.  Essentially I'm just using this block within my "home.example.com" `server` block:
```
  # proxy to foswiki via path
  location /wiki {
    proxy_pass              http://my-docker-foswiki-host.example.com:8765/;
}
```

I've also tried adding
```
proxy_set_header        X-Real-IP       $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
```
both together or individually but it doesn't seem to change anything.

I'm admittedly not an expert with configuring nginx so it's very possible I'm missing something obvious but not sure exactly where to look or the best way to debug the issues i'm encountering with this configuration. TIA!

**Comment by timlegge** [comment]
I use an nginx proxy to docker_foswiki and it works well however I have set up the nginx proxy to treat it as the site name.  For instance https:://wiki.example.com is proxied to the docker_foswiki not a sub dir.  

To get the sub dir to work you should look at the foswiki configure as it should know about the subdir I think

**Comment by smuskiew** [comment]
Thanks @timlegge I'll take another run through the foswiki configure settings.

**Comment by smuskiew** [comment]
Sticking with using the site name for now, that is working fine (I wasn't able to find a specific Foswiki setting to make the sub dir work, though admittedly I didn't dig real deep 😉 )
