### ISSUE TITLE
Unable to rebuild image due to upstream Alpine package conflicts

### ISSUE THREAD

**Issue by smuskiew** [timlegge/docker-foswiki#42]
I'm trying to test some tweaks to the `Dockerfile` using Alpine `edge` but it seems like there are some upstream Alpine packaging conflicts that prevent `docker build .` from working at all.

Seems like you've already [reported the issue against Alpine](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12165) but I don't see any feedback or resolution to the issue.

Do you have any workarounds in the meantime to get around the packaging issue?

**Comment by timlegge** [comment]
Hi

I just pushed some changes to the repo.  Take a look.  I have not seen any issues building this version.

Tim

**Comment by smuskiew** [comment]
hey Tim,

Awesome, it's building again!  Thanks for the quick response!

-steve
