### ISSUE TITLE
Build ERROR: perl-dbd-sqlite

### ISSUE THREAD

**Issue by zarafc** [timlegge/docker-foswiki#43]
Hi

Today, 09-Aug I get an error on the build

ERROR: perl-dbd-sqlite-1.70-r0: BAD signature

Anyone else see this?

**Comment by timlegge** [comment]
Hi

Did you try with the --no-cache option?

docker build --no-cache -t docker-foswiki .

Typically that is because there was a download issue.

Tim

**Comment by zarafc** [comment]
Hi
I haven't been able to re-build. I keep getting another error on Ubuntu
ERROR: https://dl-cdn.alpinelinux.org/alpine/edge/main: temporary error (try again later)

I will try later

**Comment by zarafc** [comment]
Hi Again
After sorting out my network issues I tried again with the --no-cache option.  
No problems this time with the alpine error but I still see the problem with the new perl-dbd-sqlite

```
(279/379) Installing perl-utils (5.34.0-r0)
ERROR: perl-dbd-sqlite-1.70-r0: BAD signature
```

Thanks for any feedback

**Comment by timlegge** [comment]
Hi  Definitely an alpine issue - I am tracking it down...  Likely today or tomorrow.

**Comment by timlegge** [comment]
Should be resolved now
