### ISSUE TITLE
Errors with statistics and solr - this IndexWriter is closed

### ISSUE THREAD

**Issue by zarafc** [timlegge/docker-foswiki#44]
Hi
I have recently started to get error messages from the solr index and statistics jobs

the error message includes

`ERROR: 500 Server Error: {"responseHeader":{"status":500,"QTime":1},"error":{"msg":"this IndexWriter is closed","trace":"org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed\n\tat org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:720)\n\tat `

Any suggestions? Should I delete the solr indexing? 

Thanks for your feedback

**Comment by timlegge** [comment]
Have you restarted the container?  I would start there.  There is not a lot of information on it anywhere.  

Also it might be worth looking around the running container to see if there are any obvious issues.

**Comment by zarafc** [comment]
Thanks for the feedback. I will schedule a restart the container and will let you know what happened. I dont see thin on other instances. I did however import some converted data from Confluence recently and perhaps that has had an impact

**Comment by zarafc** [comment]
After restarting the container the problem is resolved.
