### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by zarafc** [timlegge/docker-foswiki#46]
Hi 
Not really an issue , more of a suggestion to support [GenPDFAd](https://foswiki.org/Extensions/GenPDFAddOn)

I added the following to a local copy of the Dockerfile

`#PDF dependencies
RUN curl -L -o master.zip \
        https://github.com/michaelrsweet/htmldoc/archive/refs/heads/master.zip \
        && unzip master.zip -q \
        && rm master.zip \
        && mv htmldoc-master /tmp \
        && chmod -R 777 /tmp/htmldoc-master \
        && cd /tmp/htmldoc-master \
        && ./configure --silent \
        && make --silent \
        && make install
`

I got  `genpdf` to work well with the above. 
Do you think this or something similar would be useful for future version?

**Comment by timlegge** [comment]
Hi

The best approach is likely adding htmldoc to https://github.com/timlegge/docker-foswiki/blob/bd3c69b7ce4e4178ac80cde12f561e14b8c4c22d/Dockerfile#L18 and then adding

tools/extension_installer GenPDFAddOn -r -enable install && \

after

https://github.com/timlegge/docker-foswiki/blob/bd3c69b7ce4e4178ac80cde12f561e14b8c4c22d/Dockerfile#L133

You can send a pull request if you want.

Tim

**Comment by timlegge** [comment]
Added to build - please test and let me know

**Comment by zarafc** [comment]
Hi
It works. Thanks for this.
I couldn't find htmldoc  as an alpine Linux package and this is why I went through the `make ` process
