### ISSUE TITLE
Missing assets / nginx 502

### ISSUE THREAD

**Issue by 4rne** [timlegge/docker-foswiki#47]
I could not get uploaded images to show. The nginx log was indicating a missing Perl module:
`[error] 20#20: *19 FastCGI sent in stderr: "Can't locate File/MMagic/XS.pm in @INC (you may need to install the File::MMagic::XS module) (@INC contains: /var/www/foswiki/lib . /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl /var/www/foswiki/lib/CPAN/lib) at /var/www/foswiki/lib/Foswiki/Contrib/XSendFileContrib.pm line 25.`

I solved it by installing the plugin this way:
```
apk add linux-headers g++ make perl-dev
perl -MCPAN -e 'install (File::MMagic::XS)'
```

**Comment by timlegge** [comment]
Thanks - currently packaging for alpine.  I should have a new version in a few days

**Comment by timlegge** [comment]
Fixed in latest
