### ISSUE TITLE
First steps after install

### ISSUE THREAD

**Issue by mmallejac** [timlegge/docker-foswiki#5]
Hello !

Thanks for this very nice project. I am using Foswiki for quite a long time now, and this Docker image is exactly what I was looking for.

After starting the image, how can I access the `configure` page ? It looks like the admin password does not exist yet and I cannot find a way to set it up.

Thanks in advance !
Michel

**Comment by timlegge** [comment]
Resetting the Admin Password

   - sudo docker exec -it docker-foswiki /bin/sh
   - cd /var/www/foswiki/
   - tools/configure -save -set {Password}='MyPassword'

**Comment by mmallejac** [comment]
Great, thanks !
